export function prepareConstants() {
  PDE.CONST = {
    SOCKET: {
      EMIT: {
        INPUT_DIALOG: "INPUT_DIALOG",
        CREATE_DOCUMENT: "CREATE_DOCUMENT",
        UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
        DELETE_DOCUMENT: "DELETE_DOCUMENT",
        ANNOUNCEMENT: "ANNOUNCEMENT"
      },
      RESPONSE: {
        INPUT_DIALOG: "INPUT_DIALOG_RESPONSE",
        CREATE_DOCUMENT: "CREATE_DOCUMENT_RESPONSE",
        UPDATE_DOCUMENT: "UPDATE_DOCUMENT_RESPONSE",
        DELETE_DOCUMENT: "DELETE_DOCUMENT_RESPONSE"
      }
    }
  }
}